# Generated by Django 4.2.8 on 2024-09-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantprofile",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("reapply", "Reapply"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
