# Generated by Django 4.2.8 on 2024-09-23 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_sponsorship_fullpaymentupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="fullpaymentupload",
            name="applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.applicantprofile",
            ),
        ),
        migrations.AddField(
            model_name="sponsorship",
            name="applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.applicantprofile",
            ),
        ),
    ]
